site_name: CS316 Mental Health AI Project
site_description: NLP-based Mental Health Classification Research Project
site_author: Layan Alnasser
copyright: ©️ 2026 | Layan Abdualaziz Alnasser · All rights reserved

theme:
  name: material
  language: en
  icon:
    logo: material/brain
  favicon: logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky       
    - navigation.sections
    - navigation.indexes     
    - navigation.top
    - navigation.path
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - toc.follow 
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Home: index.md
  - Project Overview:
      - Introduction: introduction.md
      - Objectives: objectives.md
      - Ethical & Societal Considerations: documentation/ethics.md
  - Methodology:
      - Data Sources & Preprocessing: methodology/data.md
      - Models & Training: methodology/models.md
      - Evaluation Metrics: methodology/evaluation.md
  - Results:
      - Findings & Visualizations: results/findings.md
      - Error Analysis: results/error-analysis.md
      - Limitations: results/limitations.md
  - Deployment:
      - Application Usage: deployment/app.md
      - Installation: deployment/install.md
      - API / Interface (Optional): deployment/api.md
  - Documentation:
      - Repository Structure: documentation/repo-structure.md
      - Requirements: documentation/requirements.md
      - Future Work: documentation/future-work.md
      - Dataset: dataset.md

  - Paper & Presentation:
      - IEEE Paper: paper/paper.md
      - Presentation Slides: paper/slides.md
      - Submission Artifacts: paper/artifacts.md
  - About:
      - Contributors: about/contributors.md
      - Contact: about/contact.md


markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - sane_lists
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg 

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LayanAlnasser

extra_css:
  - styles/extra.css

plugins:
  - search
 
extra_javascript:
  - javascripts/cta-footer.js
  - javascripts/layout-toggles.js
  - javascripts/content-collapsibles.js
