site_name: CS316 Mental Health AI Project
site_description: NLP-based Mental Health Classification Research Project
site_author: Layan Alnasser

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.action.edit
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: custom
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: custom
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode

nav:
  - Home: index.md
  - Project Overview:
      - Introduction: introduction.md
      - Objectives: objectives.md
      - Ethical & Societal Considerations: ethics.md
  - Methodology:
      - Data Sources & Preprocessing: methodology/data.md
      - Models & Training: methodology/models.md
      - Evaluation Metrics: methodology/evaluation.md
  - Results:
      - Findings & Visualizations: results/findings.md
      - Error Analysis: results/error-analysis.md
      - Limitations: results/limitations.md
  - Deployment:
      - Application Usage: deployment/app.md
      - Installation: deployment/install.md
      - API / Interface (Optional): deployment/api.md
  - Documentation:
      - Repository Structure: documentation/repo-structure.md
      - Requirements: documentation/requirements.md
      - Future Work: documentation/future-work.md
      - Dataset: dataset.md

  - Paper & Presentation:
      - IEEE Paper: paper/paper.md
      - Presentation Slides: paper/slides.md
      - Submission Artifacts: paper/artifacts.md
  - About:
      - Contributors: about/contributors.md
      - Contact: about/contact.md


markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - sane_lists
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.magiclink
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LayanAlnasser

extra_css:
  - styles/extra.css

plugins:
  - search